//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssistClub.UI.Blazor.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AnswerFormResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnswerFormResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AssistClub.UI.Blazor.Resources.AnswerFormResources", typeof(AnswerFormResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ContentRequiredMessage {
            get {
                return ResourceManager.GetString("ContentRequiredMessage", resourceCulture);
            }
        }
        
        internal static string ContentMaxLengthMessage {
            get {
                return ResourceManager.GetString("ContentMaxLengthMessage", resourceCulture);
            }
        }
        
        internal static string FormSubmitButton {
            get {
                return ResourceManager.GetString("FormSubmitButton", resourceCulture);
            }
        }
        
        internal static string FormErrorMessage {
            get {
                return ResourceManager.GetString("FormErrorMessage", resourceCulture);
            }
        }
        
        internal static string FormSuccessMessage {
            get {
                return ResourceManager.GetString("FormSuccessMessage", resourceCulture);
            }
        }
        
        internal static string FormUserNotFoundMessage {
            get {
                return ResourceManager.GetString("FormUserNotFoundMessage", resourceCulture);
            }
        }
        
        internal static string ComponentTitle {
            get {
                return ResourceManager.GetString("ComponentTitle", resourceCulture);
            }
        }
        
        internal static string FormContentEmptyMessage {
            get {
                return ResourceManager.GetString("FormContentEmptyMessage", resourceCulture);
            }
        }
    }
}
