//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssistClub.UI.Blazor.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AskQuestionResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AskQuestionResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AssistClub.UI.Blazor.Resources.AskQuestionResources", typeof(AskQuestionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        internal static string FormTitleLabel {
            get {
                return ResourceManager.GetString("FormTitleLabel", resourceCulture);
            }
        }
        
        internal static string TitleHint {
            get {
                return ResourceManager.GetString("TitleHint", resourceCulture);
            }
        }
        
        internal static string FormTitlePlaceholder {
            get {
                return ResourceManager.GetString("FormTitlePlaceholder", resourceCulture);
            }
        }
        
        internal static string FormContentLabel {
            get {
                return ResourceManager.GetString("FormContentLabel", resourceCulture);
            }
        }
        
        internal static string FormContentHint {
            get {
                return ResourceManager.GetString("FormContentHint", resourceCulture);
            }
        }
        
        internal static string FormSubmitButton {
            get {
                return ResourceManager.GetString("FormSubmitButton", resourceCulture);
            }
        }
        
        internal static string FormErrorMessage {
            get {
                return ResourceManager.GetString("FormErrorMessage", resourceCulture);
            }
        }
        
        internal static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        internal static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        internal static string ContentMaxLengthMessage {
            get {
                return ResourceManager.GetString("ContentMaxLengthMessage", resourceCulture);
            }
        }
        
        internal static string ContentRequiredMessage {
            get {
                return ResourceManager.GetString("ContentRequiredMessage", resourceCulture);
            }
        }
        
        internal static string TitleMaxLengthMessage {
            get {
                return ResourceManager.GetString("TitleMaxLengthMessage", resourceCulture);
            }
        }
        
        internal static string TitleRequiredMessage {
            get {
                return ResourceManager.GetString("TitleRequiredMessage", resourceCulture);
            }
        }
        
        internal static string FormUserErrorMessage {
            get {
                return ResourceManager.GetString("FormUserErrorMessage", resourceCulture);
            }
        }
        
        internal static string FormFileLabelWithSize {
            get {
                return ResourceManager.GetString("FormFileLabelWithSize", resourceCulture);
            }
        }
        
        internal static string SuggestedQuestionsTitle {
            get {
                return ResourceManager.GetString("SuggestedQuestionsTitle", resourceCulture);
            }
        }
    }
}
