//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssistClub.UI.Blazor.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DateTimeResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DateTimeResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AssistClub.UI.Blazor.Resources.DateTimeResources", typeof(DateTimeResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string TimeAgoUnknown {
            get {
                return ResourceManager.GetString("TimeAgoUnknown", resourceCulture);
            }
        }
        
        internal static string TimeAgoJustNow {
            get {
                return ResourceManager.GetString("TimeAgoJustNow", resourceCulture);
            }
        }
        
        internal static string TimeAgoMinutes {
            get {
                return ResourceManager.GetString("TimeAgoMinutes", resourceCulture);
            }
        }
        
        internal static string TimeAgoHours {
            get {
                return ResourceManager.GetString("TimeAgoHours", resourceCulture);
            }
        }
        
        internal static string TimeAgoDays {
            get {
                return ResourceManager.GetString("TimeAgoDays", resourceCulture);
            }
        }
        
        internal static string TimeAgoMonths {
            get {
                return ResourceManager.GetString("TimeAgoMonths", resourceCulture);
            }
        }
        
        internal static string TimeAgoYears {
            get {
                return ResourceManager.GetString("TimeAgoYears", resourceCulture);
            }
        }
    }
}
