//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssistClub.UI.Blazor.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProfileResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProfileResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AssistClub.UI.Blazor.Resources.ProfileResources", typeof(ProfileResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string FullnameLabel {
            get {
                return ResourceManager.GetString("FullnameLabel", resourceCulture);
            }
        }
        
        internal static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        internal static string PhotoLabel {
            get {
                return ResourceManager.GetString("PhotoLabel", resourceCulture);
            }
        }
        
        internal static string ClubLabel {
            get {
                return ResourceManager.GetString("ClubLabel", resourceCulture);
            }
        }
        
        internal static string MicrositeLabel {
            get {
                return ResourceManager.GetString("MicrositeLabel", resourceCulture);
            }
        }
        
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        internal static string TabProfileLabel {
            get {
                return ResourceManager.GetString("TabProfileLabel", resourceCulture);
            }
        }
        
        internal static string TabActivityLabel {
            get {
                return ResourceManager.GetString("TabActivityLabel", resourceCulture);
            }
        }
    }
}
