//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssistClub.UI.Blazor.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QuestionResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuestionResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AssistClub.UI.Blazor.Resources.QuestionResources", typeof(QuestionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        internal static string StatusLabel {
            get {
                return ResourceManager.GetString("StatusLabel", resourceCulture);
            }
        }
        
        internal static string AskedLabel {
            get {
                return ResourceManager.GetString("AskedLabel", resourceCulture);
            }
        }
        
        internal static string AskedByLabel {
            get {
                return ResourceManager.GetString("AskedByLabel", resourceCulture);
            }
        }
        
        internal static string NotFoundTitle {
            get {
                return ResourceManager.GetString("NotFoundTitle", resourceCulture);
            }
        }
        
        internal static string EditQuestionDialogTitle {
            get {
                return ResourceManager.GetString("EditQuestionDialogTitle", resourceCulture);
            }
        }
        
        internal static string UpdateQuestionSuccessMessage {
            get {
                return ResourceManager.GetString("UpdateQuestionSuccessMessage", resourceCulture);
            }
        }
        
        internal static string UpdateQuestionErrorMessage {
            get {
                return ResourceManager.GetString("UpdateQuestionErrorMessage", resourceCulture);
            }
        }
        
        internal static string EditQuestionButton {
            get {
                return ResourceManager.GetString("EditQuestionButton", resourceCulture);
            }
        }
        
        internal static string DeleteQuestionButton {
            get {
                return ResourceManager.GetString("DeleteQuestionButton", resourceCulture);
            }
        }
        
        internal static string DeleteQuestionConfirmMessage {
            get {
                return ResourceManager.GetString("DeleteQuestionConfirmMessage", resourceCulture);
            }
        }
        
        internal static string DeleteQuestionConfirmTitle {
            get {
                return ResourceManager.GetString("DeleteQuestionConfirmTitle", resourceCulture);
            }
        }
        
        internal static string DeleteQuestionSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteQuestionSuccessMessage", resourceCulture);
            }
        }
        
        internal static string DeleteQuestionErrorMessage {
            get {
                return ResourceManager.GetString("DeleteQuestionErrorMessage", resourceCulture);
            }
        }
        
        internal static string DownloadAttachmentButton {
            get {
                return ResourceManager.GetString("DownloadAttachmentButton", resourceCulture);
            }
        }
        
        internal static string AttachmentAltText {
            get {
                return ResourceManager.GetString("AttachmentAltText", resourceCulture);
            }
        }
        
        internal static string FormFileChooseButton {
            get {
                return ResourceManager.GetString("FormFileChooseButton", resourceCulture);
            }
        }
        
        internal static string FormFileLabelWithSize {
            get {
                return ResourceManager.GetString("FormFileLabelWithSize", resourceCulture);
            }
        }
    }
}
