//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssistClub.UI.Blazor.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserSettingsResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserSettingsResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AssistClub.UI.Blazor.Resources.UserSettingsResources", typeof(UserSettingsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NotifyOnNewClubQuestionLabel {
            get {
                return ResourceManager.GetString("NotifyOnNewClubQuestionLabel", resourceCulture);
            }
        }
        
        internal static string NotifyOnAnswerPublishedOnMyQuestionLabel {
            get {
                return ResourceManager.GetString("NotifyOnAnswerPublishedOnMyQuestionLabel", resourceCulture);
            }
        }
        
        internal static string NotifyOnAnswerToMyQuestionMarkedOfficialLabel {
            get {
                return ResourceManager.GetString("NotifyOnAnswerToMyQuestionMarkedOfficialLabel", resourceCulture);
            }
        }
        
        internal static string NotifyOnMyQuestionOrAnswerModifiedByAdminLabel {
            get {
                return ResourceManager.GetString("NotifyOnMyQuestionOrAnswerModifiedByAdminLabel", resourceCulture);
            }
        }
        
        internal static string NotifyOnAnyOfficialAnswerInQuestionIrelatedLabel {
            get {
                return ResourceManager.GetString("NotifyOnAnyOfficialAnswerInQuestionIrelatedLabel", resourceCulture);
            }
        }
        
        internal static string NotifyOnQuestionIrelatedModifiedByAuthorLabel {
            get {
                return ResourceManager.GetString("NotifyOnQuestionIrelatedModifiedByAuthorLabel", resourceCulture);
            }
        }
        
        internal static string NotifyOnNewAnswerInQuestionIrelatedLabel {
            get {
                return ResourceManager.GetString("NotifyOnNewAnswerInQuestionIrelatedLabel", resourceCulture);
            }
        }
        
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        internal static string OnLabel {
            get {
                return ResourceManager.GetString("OnLabel", resourceCulture);
            }
        }
        
        internal static string OffLabel {
            get {
                return ResourceManager.GetString("OffLabel", resourceCulture);
            }
        }
        
        internal static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
    }
}
